// Generates seed.sql from the iOS app's mock JSON files.
// Usage: node generate-seed.js
const fs = require('fs');
const path = require('path');

const mockDir = path.join(__dirname, '..', 'SpillTheBeans', 'Resources', 'MockData');
const coffees = JSON.parse(fs.readFileSync(path.join(mockDir, 'coffees.json'), 'utf8'));
const shops   = JSON.parse(fs.readFileSync(path.join(mockDir, 'coffeeShops.json'), 'utf8'));

const q = (v) => v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

let sql = '-- Generated by generate-seed.js — do not edit by hand\n';

for (const c of coffees) {
  sql += `INSERT INTO coffees (id, name, origin_country, origin_region, origin_flag, process, roast_level, flavor_tags, tasting_note, producer, altitude, harvest_season) VALUES (` +
    [q(c.id), q(c.name), q(c.origin.country), q(c.origin.region), q(c.origin.flag),
     q(c.process), q(c.roastLevel), q(JSON.stringify(c.flavorTags)), q(c.tastingNote),
     q(c.producer), q(c.altitude), q(c.harvestSeason)].join(', ') + `);\n`;
}

for (const s of shops) {
  sql += `INSERT INTO coffee_shops (id, name, address, latitude, longitude, category, rating, opening_hours, roaster_info, description, tags) VALUES (` +
    [q(s.id), q(s.name), q(s.address), s.latitude, s.longitude, q(s.category), s.rating,
     q(JSON.stringify(s.openingHours)), q(s.roasterInfo), q(s.description),
     q(JSON.stringify(s.tags))].join(', ') + `);\n`;
}

// ── Seed reviews (mirrors the old MockReviewService pools) ───────────────────
const usernames = [
  'barista.james', 'coffeelena', 'brew.maven', 'pour_max',
  'espresso.finn', 'morning.roast', 'slowbrew.sara', 'coffeenerd42',
  'thirdwave.tom', 'beanwhisperer',
];
const notes = [
  "Absolutely stunning clarity. Best pour over I've had this year.",
  'The floral notes really shine as an espresso. Surprisingly complex.',
  'Made this as a flat white — the sweetness balanced the milk perfectly.',
  'Tried it as cold brew overnight. Very smooth and low acidity.',
  'A bit too light for my taste in a latte, but beautiful as a pour over.',
  'Really brought out the fruity notes with AeroPress. Highly recommend.',
  'Clean, bright, and refreshing. Will definitely order again.',
  'The chocolate undertones are incredible in a French press.',
  'Excellent balance. Works beautifully in every brew method I have tried.',
  'Floral and delicate. A very special cup.',
  'Beautiful for slow mornings — very meditative brew.',
  'Incredible aroma. My go-to morning pour over bean.',
];
const brews = ['Pour Over', 'Espresso', 'Flat White', 'Latte', 'Cappuccino',
               'Cortado', 'AeroPress', 'French Press', 'Cold Brew', 'Chemex'];

// Deterministic xorshift so re-running produces identical seed data.
let state = 0x5DEECE66Dn;
function rnd(max) {
  state ^= state << 13n; state &= 0xFFFFFFFFFFFFFFFFn;
  state ^= state >> 7n;
  state ^= state << 17n; state &= 0xFFFFFFFFFFFFFFFFn;
  return Number(state % BigInt(max));
}

let reviewNum = 0;
for (const c of coffees) {
  const count = 3 + rnd(5); // 3–7 reviews per coffee
  for (let i = 0; i < count; i++) {
    reviewNum++;
    // Must be valid UUID hex — the iOS app decodes this into a Swift UUID.
    const id = `AB000000-0000-4000-8000-${String(reviewNum).padStart(12, '0')}`;
    const username = usernames[rnd(usernames.length)];
    const daysAgo = 1 + rnd(120);
    const date = new Date(Date.now() - daysAgo * 86400_000).toISOString();
    sql += `INSERT INTO reviews (id, coffee_id, user_id, username, brew_method, rating, note, created_at) VALUES (` +
      [q(id), q(c.id), q('u_' + username), q(username), q(brews[rnd(brews.length)]),
       3 + rnd(3), q(notes[rnd(notes.length)]), q(date)].join(', ') + `);\n`;
  }
}

fs.writeFileSync(path.join(__dirname, 'seed.sql'), sql);
console.log(`seed.sql written: ${coffees.length} coffees, ${shops.length} shops, ${reviewNum} reviews`);
