name = "spillthebeans-auth"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "USERS"
id = "d54032cae9f44c5aa6f4ea2ecce5c6b8"

[[kv_namespaces]]
binding = "SESSIONS"
id = "fd8f8e9f73484d6499d5e31b08983a0e"
